### ISSUE TITLE
New Output Gain textboxes don't work well on Windows

### ISSUE THREAD

**Issue by starslab** [munt/munt#110]
MUNT wants to ensure these textboxes have `x.xx` in them at all times, and it makes text entry difficult and frustrating on Windows.

I'm not sure how to explain this, so I'm going to use an example. Let's say I want to set Output Gain to 0.75

Expected Behavior:
I should be able to triple-click to select the contents of the entire box, or click-and-drag across it. This mostly works as expected. 
I should then be able to type `0.75` to enter the desired value

Actual Behavior:
The text box scrolls left-to-right because it's slightly too small for the text contained within it, which can complicate swiping across the box with the mouse.

Typing doesn't work and hitches up. When I type `0`, MUNT automatically populates `0.00`, when I type `.` MUNT lets the cursor advance past the decimal. Further typing `75` doesn't do anything, because the box is already populated with `00`.

Is it possible for the program to have that textbox be in overwrite mode, rather than insert mode?

**Comment by sergm** [comment]
Follow-up for #104
