### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by robrich82** [munt/munt#123]
Is it possible to set two copies of Munt with separate MIDI ports and running different roms?

I.e. have one running the old MT-32 and another the CM-32L?

**Comment by sergm** [comment]
Of course, that's possible. There is no need to run more than one instance even: mt32emu-qt supports multiple synths, each can be configured with a distinct "profile" that includes a set of ROMs.

If you still prefer running several applications nevertheless, note that there is a limitation on Windows platform. Only one of the started instances of mt32emu-qt will communicate with the Windows MIDI driver. The other instances have to rely on externally provided MIDI-in ports.

**Comment by robrich82** [comment]
Ah thank you so much. Got it working now!
