### ISSUE TITLE
Implement support for bitwise ROM dumps

### ISSUE THREAD

**Issue by sergm** [munt/munt#44]
Currently, the library is only capable of loading _post-processed_ ROM images that resulted from interleaving the original files with ROM IC dumps each of which contain bytes written to either even or odd addresses. This implies that the user has not to merely dump the contents of the ICs but also merge the corresponding "halves" into one complete file.

OTOH, when the ROMInfo class was first introduced, it was already foreseen to register those "raw" files with bitwise ROM dumps with the intention to create a complete ROM image automatically from several files, provided they are identified.

**Task**: Add support for handling multi-file ROM images as appropriate and add the metadata for known bitwise dumps of ROM ICs.

**Comment by kcgen** [comment]
Thanks for supporting the original bitwise ROM dump format, @sergm!
We will use your new functionality to let users select a specific model and version to load, assuming they have a pool of uniquely named ROMs. 
Regards.

**Comment by sergm** [comment]
You welcome :)
If you encounter an oddness in the new API, please let me know before I close the issues and tag a new lib version.

**Comment by kcgen** [comment]
> If you encounter an oddness in the new API, please let me know before I close the issues and tag a new lib version.

@sergm , wanted to report that I've confirmed positive use all sets of bitwise ROM dumps (MT-32 1.04 through Blue Ridge, and CM-32L 1.00 and 1.02), using the `identifyROMFile` and `mergeAndAddROMFiles` functions.

From Staging's needs, we're all set to use this once you tag and release it!

**Comment by kcgen** [comment]
The only version I haven't tested is MT-32 2.04. because it's not part of the MAME MT-32 or CL-32L sets.
Have you been able to find it?

**Comment by sergm** [comment]
> @sergm , wanted to confirm that your bitwise ROM handling routines are working perfectly. In DOSBox Staging branch https://github.com/dosbox-staging/dosbox-staging/tree/kc/versioned-mt32-1, I've tested MT-32 1.04 through Blue Ridge, and CM-32L 1.00 and 1.02 using the `identifyROMFile` and `mergeAndAddROMFiles` functions, including played games with them.
> 
> From Staging's perspective, we're all set for 2.5.0!

Great news, I'll bump version 2.5.0 then.

> The only version I haven't tested is MT-32 2.04 because it's not part of the MAME MT-32 or CL-32L sets.
> Have you been able to find it?

Yes, I've also confirmed the validity of my ROM dump with @dwhinham (our dump matched), so I'm pretty sure about it. Note, however, the control ROM IC of the new-gen unit isn't split (which can be seen in the service notes v.3).

**Comment by kcgen** [comment]
Thank you @sergm!
