### ISSUE TITLE
Cannot download MT32Emu-qt-1.8.0.dmg from Munt sourceforge.net

### ISSUE THREAD

**Issue by wyatt-wong** [munt/munt#49]
I cannot download MT32Emu-qt-1.8.0.dmg from Munt sourceforge.net and got the following error:

<img width="1091" alt="Screen Shot 2021-02-17 at 9 32 46 PM" src="https://user-images.githubusercontent.com/10095648/108211578-cf64ec00-7167-11eb-88db-df8ede0e0e75.png">

**Comment by sergm** [comment]
Seems like you've caught sourceforge at a bad time. Now the file should be available, I can download it.

**Comment by sergm** [comment]
Closed as obsolete.
