### ISSUE TITLE
(minor) ROMImage should be freed with `delete[]` to match its `new[]` allocation

### ISSUE THREAD

**Issue by kcgen** [munt/munt#60]
The Address Sanitizer caught this:

![2021-05-21_17-12](https://user-images.githubusercontent.com/1557255/119208603-e0b7e000-ba57-11eb-82b2-209261f3fea5.png)

In ROMInfo.cpp, `romImage`'s memory is allocated on line 227 with `new[]`:

``` c++
Bit8u *data = new Bit8u[2 * partSize];
```

But it's released with `delete` (instead of `delete[]`) on line 273:

``` c++
delete romImage;
```

**Comment by sergm** [comment]
> But it's released with `delete` (instead of `delete[]`) on line 273:
> 
> ```c++
> delete romImage;
> ```

That's not it. The problematic delete is at #250
`delete data;`
which is a byte array... And all my code analysers are silent :/

**Comment by sergm** [comment]
@kcgen Please see if this is now fixed.

**Comment by kcgen** [comment]
That did it!

**Comment by sergm** [comment]
You welcome!
