### ISSUE TITLE
OSX binary

### ISSUE THREAD

**Issue by landloafer** [munt/munt#63]
Can I request binary compiled for or compatible with OS X El Capitan 10.11.6?

**Comment by sergm** [comment]
I think this should be very possible. Albeit, I'm not sure what is the Qt version that supported it, so it may take a bit of time to sort out.

**Comment by sergm** [comment]
I uploaded a bundle that includes Qt 5.9.9 [here](https://sourceforge.net/projects/munt/files/munt/2.5.0/macOS/old_platforms/). Please see if it works for you. But indeed, that stuff completely lacks support these days...

**Comment by landloafer** [comment]
Thanks for an update. However, I cannot make it work. I think the format of this DMG package cannot be handled by the diskimagemounter on El Capitan.

**Comment by sergm** [comment]
If only I remembered the code of the supported format... Will repack as I find it 😀

**Comment by sergm** [comment]
Repacked as UDBZ, so it should open even on 10.10.

**Comment by landloafer** [comment]
This is highly appreciated. It works perfectly.

**Comment by landloafer** [comment]
Hi,
Further request a OS X El Capitan 10.11.6 binary, if possible? Very much appreciated.

**Comment by sergm** [comment]
I suppose, it should be possible still, albeit the recent Qt versions do not even compile with this Mac SDK, AFAICT. So it will fall into the support for "legacy" system. Let me see how it goes...

**Comment by sergm** [comment]
Done, you can find it [here](https://sourceforge.net/projects/munt/files/munt/2.7.0/macOS/old_platforms/). As usual, please ping me if it's broken, etc.

**Comment by landloafer** [comment]
It doesn't open. I attached the crash report here.

[munt.crash.report.txt](https://github.com/munt/munt/files/9539433/munt.crash.report.txt)

**Comment by sergm** [comment]
Hopefully  fixed.

**Comment by landloafer** [comment]
It works great now! Many thanks.
