### ISSUE TITLE
Improve CMake build scripts

### ISSUE THREAD

**Issue by sergm** [munt/munt#65]
CMake build system should try its best at facilitating the search for the applicable dependencies. Notably, that includes checks for required version of components to ensure API compatibility.

Additionally, libmt32emu should make adding it to consumer applications easier in case they are also rely on the CMake build system. Providing a FindPackage module FindMT32EMU.cmake is discouraged, so that shall be replaced with a proper CMake configuration file, which also makes it easy to retrieve transitive dependencies (when applicable) and correct version information.

**Comment by dreamer** [comment]
@sergm I suggest you spend some time investigating Meson - perhaps switching the buildsystem will be beneficial for the project.

**Comment by sergm** [comment]
I did look at Meson some time ago. Being based on a multi-purpose language, it seems powerful, somewhat similar to gradle and waf in spirit, I think. But atm, there is no plan to switch, as CMake seems well supported, widely available and "it does its work" so far... It'd be a good choice a while ago, when we got away from autotools, though.

**Comment by AndersonTorres** [comment]
Correct me if I'm wrong, but according to this, all multiple projects/packages inside this monorepo will receive the same numbered version tag?

**Comment by sergm** [comment]
Well... To be fair, there is no strict relation between version numbers among the projects, except the fact that the "munt" tag currently matches the library version. Maybe a better idea would be to use the year.release scheme here, I'm not too sure yet.

And yes, all tags are indeed visible in a single git repo, but each tag is prefixed with the project ID, so we may distinguish what project exactly is tagged.
