### ISSUE TITLE
DosBox + Munt hangs Toshiba Satelitte L670 (AMD HDMI?) audio driver.

### ISSUE THREAD

**Issue by SkybuckFlying** [munt/munt#73]
DosBox + Munt hang the audio driver of this Laptop which is very annoying and requires many resets.

The hang of the audio driver/default IME is most likely caused when switching between window and full screen and also on exit.

OS Is Windows 7 Home edition.

It also prevents Firefox from playing any videos and it will also crash firefox and any other audio application until a reboot is done.

Tried to disable audio device and tried to restart audio service but this doesn't work/help. Very strange windows issue/driver issue.

I am willing to run a debug build of either dosbox or munt to try and diagnose this problem.

AMD HDMI driver is probably culprit, the same behaviour is witnessed when playing Predator Hunting Ground.

Sometimes 7.1 configuration also has to be re-done plus volume adjustment cause it goes to 100%.

All in all this is a major pain in the ass to deal with, fortunately I configured the laptop to reboot fast otherwise this would be an insane problem.

**Comment by sergm** [comment]
I could only think of some latency settings that are unfortunate for the poor driver. It could be that increasing latency will make it happy, or maybe switching the audio backend.

**Comment by SkybuckFlying** [comment]
I am not yet sure if dosbox itself is the problem or munt... but is there any setting in munt which I can change ? I already tried a different rom set. I will have to do more testing with dosbox to see if it is the culprit. I tried disabling aero theme in windows has no effect. I did change output=ddraw in dosbox conf to solve color issues when alt-tabbing/full screen... hmmm tried dosbox 0.65 and dosbox 0.74-3 both have same problem with audio driver hanging after usage. Not sure if I can disable munt such that dosbox stops using it to detect if it truely is a problem with munt... but seems somewhat likely.

I could also try and run everything in windows 11 inside a virtual box/vm to see if that performs any different lol :)

**Comment by SkybuckFlying** [comment]
I will give DosBosX a try it claims to have build-in MT32 support, I am not sure if this was done by integrating the munt code ?

**Comment by SkybuckFlying** [comment]
OK So far DosBoxX seems to work, I went with Roland SC-55 sound font for now because that is what this game Master Of Orion uses:

https://github.com/trevor0402/SC55Soundfont/releases

So  far music and sound is working well, maybe later I try MT-32 again :)

**Comment by sergm** [comment]
Sorry, I have no clue what your setup is, but the rant above suggests you were trying a vanilla DOSBox with maybe mt32emu driver for Windows multimedia. If that's the case, I would also consider a possibility that the audio device simply works in the exclusive mode, so only one application may play audio at a time. If you're still interested, please provide more details on what exactly setup you want to make working.

**Comment by sergm** [comment]
Timed out.
