### ISSUE TITLE
[FEATURE] Allow single audio channel isolation

### ISSUE THREAD

**Issue by Hyperbog** [munt/munt#77]
Hey folks! This is a feature request (unless it exists, and I'm just missing it...). 

I have the standalone Munt emulator, and see that it can differentiate between different audio channels based on the instrument that's playing / MIDI channel that's being triggered. Would it be possible to implement, say, a mute checkbox next to each channel so that one could record / export each channel individually by isolating each channel? This would be great for folks like myself who can then import those tracks into a DAW, and give them a more modern upscaled mix for lack of a better term. Original audio. Original arrangements. Just higher quality. 

Anyhoo. Munt sounds fantastic. If this feature is possible to implement it would be absolutely perfect for what I'm looking for! Thanks!

**Comment by sergm** [comment]
We seemingly get one more function here - a possibility to adjust the part volume and keep it at the desired level regardless of whether we get the MIDI Volume controller and related SysEx. This function has been requested in [Feature 31](https://sourceforge.net/p/munt/feature-requests/31/) and is tightly related to this one.

**Comment by Hyperbog** [comment]
That's a great idea, and makes it even more like a mixer channel strip in a DAW between your improvement on my suggestion for a [M]ute and [S]olo toggle and the suggestion cited in Feature 31 for individual volume sliders. Once these features are implemented I will start giving those old soundtracks a fresh mix. Who knows maybe down the road custom music packs can be loaded along with the game. There's a very early version of that kind of feature being implemented in an NES emulator that I can't think of at the moment....
