### ISSUE TITLE
[mt32emu] provide a CMake config to easily include it as a library in other CMake projects

### ISSUE THREAD

**Issue by Raffaello** [munt/munt#81]
Hi,

It looks like that there is no Cmake config to easily include mt32emu as a dependency like for e.g.:
`find(libMT32emu CONFIG REQUIRED)` and then be "ready to be used".

I have opened a similar issue in vcpkg that is providing libmt32emu, but it is not really convinient without a CMake config.
Here as a reference:
https://github.com/microsoft/vcpkg/issues/22273

Would it be possible to include a CMake config to simplify the use and configuration of the library?
(thanks)

**Comment by sergm** [comment]
Yes, this is scheduled for libmt32emu_2_6 and implemented in #65, so expect it to be available in short term.

**Comment by sergm** [comment]
Closed as obsolete.
